apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: lfnet-staging

resources:
  - lfweb.yaml
  - redclay.yaml
  - shufflebot.yaml

patchesStrategicMerge:
  - lfweb_private_service_endpoint.yaml
  - redclay_private_service_endpoint.yaml
