apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: flurrybot
  labels:
    app: flurrybot
spec:
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: flurrybot
            image: epilanthanomai/flurrybot:0.1
            command: ["/bin/sh", "./generate.sh"]
            env:
            - name: MASTO_TOKEN
              valueFrom:
                secretKeyRef:
                  name: flurrybot-credentials
                  key: apikey
            - name: MASTO_BASE_URL
              value: https://botsin.space/
          restartPolicy: OnFailure
